name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true

    - name: Build
      run: go build ./...

    - name: Build CLI binary
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          go build -o cmd/acousticalc/acousticalc.exe cmd/acousticalc/main.go
        else
          go build -o cmd/acousticalc/acousticalc cmd/acousticalc/main.go
        fi
      shell: bash

    - name: Test
      run: go test ./...
